baseURL = 'https://unnamed-rpg.pages.dev/'
languageCode = 'en-us'
title = 'Game?'
theme = 'mytheme'

[module]
    [[module.mounts]]
        source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
        target = "assets/js/bootstrap.bundle.min.js"